apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pythonSimpleApp.appName }}-service
spec:
  selector:
    app: {{ .Values.pythonSimpleApp.appName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
