replicaCount: 1

pythonSimpleApp:
  appName: python-simple-app
  tag: python-simple-app
  host: python-simple-app.jabz.fr

  resources:
    requests:
      memory: "50Mi"
      cpu: "20m"
    limits:
      memory: "100Mi"
      cpu: "40m"
